### ISSUE TITLE
Wrong interface name and trait name in documentation

### ISSUE THREAD

**Issue by stormfly-pl** [ebittleman/monolog-zf2#1]
I found a small bug in the documentation

```
class ExampleService implements LogAwareInterface
{
    use LogAwareTrait;
```

should be:

```
class ExampleService implements LoggerAwareInterface
{
    use LoggerAwareTrait;
```

**Comment by ebittleman** [comment]
Hey thanks, feel free to submit a pull request to make the update. How's everything else working out for you?

**Comment by stormflypl** [comment]
In my opinion it's great work :+1:  There is only one problem, what do you think about adding formatters? I can prepare the code if you are interested.

**Comment by ebittleman** [comment]
@stormflypl Its honestly been a long while since ive looked at this library. If you'd like to submit a pull request to add formatters please feel free to. Thanks!
